### ISSUE TITLE
sqlite3.OperationalError: no such table: snapshots

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/ethsnap#1]
Traceback (most recent call last):
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "./ethsnap.py", line 66, in index
        s.fetch()
      File "./ethsnap.py", line 52, in fetch
        self._get_snapshots(limit)
      File "./ethsnap.py", line 35, in _get_snapshots
        LIMIT :limit""", {'limit': limit})
    sqlite3.OperationalError: no such table: snapshots

**Comment by mikeshultz** [comment]
Improperly deployed.  Should you get past that, however, the site doesn't cope with having no snapshots yet: 

    Traceback (most recent call last):
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/_compat.py", line 33, in reraise
        raise value
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "./ethsnap.py", line 67, in index
        return render_template("index.html", **{'files': s.snapshots, 'analytics_id': ANALYTICS_ID, })
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/templating.py", line 134, in render_template
        context, ctx.app)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/flask/templating.py", line 116, in _render
        rv = template.render(context)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/var/www/ethsnap/ethsnap/templates/index.html", line 22, in top-level template code
        <div class="filename"><a href="/archives/main/{{ files.0.file }}" onclick="ga('send', 'event', 'Download', 'Download', 'chaindata', 1);">{{ files.0.file }}</a></div>
      File "/var/venvs/ethsnap/lib64/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
        return getattr(obj, attribute)
    jinja2.exceptions.UndefinedError: list object has no element 0

**Comment by mikeshultz** [comment]
Fixed in 7f57a53b
